-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.activite
(
    id_activite bigint NOT NULL DEFAULT nextval('activite_id_activite_seq'::regclass),
    date_debut date,
    date_fin date,
    description character varying(255) COLLATE pg_catalog."default",
    etat boolean,
    titre character varying(255) COLLATE pg_catalog."default",
    id_type_activite bigint,
    CONSTRAINT activite_pkey PRIMARY KEY (id_activite)
);

CREATE TABLE IF NOT EXISTS public.administrateur
(
    id_user bigint NOT NULL,
    CONSTRAINT administrateur_pkey PRIMARY KEY (id_user)
);

CREATE TABLE IF NOT EXISTS public.exercice
(
    id_exercice bigint NOT NULL DEFAULT nextval('exercice_id_exercice_seq'::regclass),
    annee integer,
    date_debut date,
    date_fin date,
    statut boolean,
    CONSTRAINT exercice_pkey PRIMARY KEY (id_exercice)
);

CREATE TABLE IF NOT EXISTS public.exercice_activite
(
    id_exercice bigint NOT NULL,
    id_activite bigint NOT NULL,
    CONSTRAINT exercice_activite_pkey PRIMARY KEY (id_exercice, id_activite)
);

CREATE TABLE IF NOT EXISTS public.participant
(
    fullname character varying(255) COLLATE pg_catalog."default",
    structure character varying(255) COLLATE pg_catalog."default",
    id_user bigint NOT NULL,
    id_responsable bigint,
    CONSTRAINT participant_pkey PRIMARY KEY (id_user)
);

CREATE TABLE IF NOT EXISTS public.participant_activite
(
    id_participant bigint NOT NULL,
    id_activite bigint NOT NULL,
    CONSTRAINT participant_activite_pkey PRIMARY KEY (id_participant, id_activite)
);

CREATE TABLE IF NOT EXISTS public.responsable
(
    domaine character varying(255) COLLATE pg_catalog."default",
    etat boolean,
    id_user bigint NOT NULL,
    id_type_responsable bigint,
    CONSTRAINT responsable_pkey PRIMARY KEY (id_user)
);

CREATE TABLE IF NOT EXISTS public.typeactivite
(
    id_type_activite bigint NOT NULL DEFAULT nextval('typeactivite_id_type_activite_seq'::regclass),
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT typeactivite_pkey PRIMARY KEY (id_type_activite)
);

CREATE TABLE IF NOT EXISTS public.typeresponsable
(
    id_type_responsable bigint NOT NULL DEFAULT nextval('typeresponsable_id_type_responsable_seq'::regclass),
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT typeresponsable_pkey PRIMARY KEY (id_type_responsable)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id_user bigint NOT NULL DEFAULT nextval('users_id_user_seq'::regclass),
    email character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    telephone character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id_user)
);

ALTER TABLE IF EXISTS public.activite
    ADD CONSTRAINT fk9jkwy1gdcuoc0y96jiywmixg2 FOREIGN KEY (id_type_activite)
    REFERENCES public.typeactivite (id_type_activite) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.administrateur
    ADD CONSTRAINT fkbfg0mrkw8wxr4hri3r744apn2 FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS administrateur_pkey
    ON public.administrateur(id_user);


ALTER TABLE IF EXISTS public.exercice_activite
    ADD CONSTRAINT fk4ai2ows5j79i8ueswt95jmjmp FOREIGN KEY (id_exercice)
    REFERENCES public.exercice (id_exercice) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exercice_activite
    ADD CONSTRAINT fkpw4wbdxkqypux3nqdl9l6tj6t FOREIGN KEY (id_activite)
    REFERENCES public.activite (id_activite) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participant
    ADD CONSTRAINT fkkhsyl9rjy8q0qdftg83ixjwkp FOREIGN KEY (id_responsable)
    REFERENCES public.responsable (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participant
    ADD CONSTRAINT fks351948afpak1jwuas2ch60uu FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS participant_pkey
    ON public.participant(id_user);


ALTER TABLE IF EXISTS public.participant_activite
    ADD CONSTRAINT fkca3rl0lt183v9at5uot1qodie FOREIGN KEY (id_participant)
    REFERENCES public.participant (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participant_activite
    ADD CONSTRAINT fkr8ml5n2cmk3j52abltnkalrle FOREIGN KEY (id_activite)
    REFERENCES public.activite (id_activite) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.responsable
    ADD CONSTRAINT fk13k7ffirgde8re8oy5lnveior FOREIGN KEY (id_type_responsable)
    REFERENCES public.typeresponsable (id_type_responsable) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.responsable
    ADD CONSTRAINT fk98km83ij03kwv2yk1r9ueqnt5 FOREIGN KEY (id_user)
    REFERENCES public.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS responsable_pkey
    ON public.responsable(id_user);

END;